{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quizbot.secretName" . }}
  labels:
    {{- include "quizbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecretKey }}: {{ .Values.botToken | quote }}
{{- end }}
